#cambiar el nombre de esta archivo a docker-compose.yml
version: '3.7'

services:
  db:
    image: postgres
    volumes:
      - ./data/db:/var/lib/postgresql/data
    environment:
      - POSTGRES_DB=tuclavedb           #aqui las credenciales que quieras
      - POSTGRES_USER=tuclaveuser       #aqui las credenciales que quieras
      - POSTGRES_PASSWORD=tuclavepass   #aqui las credenciales que quieras 
  django_gunicorn:
    volumes:
      - static:/static
    env_file:
      - .env
    build:
      context: .
    ports:
      - "8000:8000"
    environment:
      - POSTGRES_NAME=tuclavedb      #aqui las credenciales que quieras
      - POSTGRES_USER=tuclaveuser    #aqui las credenciales que quieras
      - POSTGRES_PASSWORD=tuclavedb  #aqui las credenciales que quieras
    depends_on:
      - db
  nginx:
    build: ./nginx
    volumes:
      - static:/static
    ports:
      - "80:80"
    depends_on:
      - django_gunicorn

volumes:
  static:

